# Cloud Build configuration for WARLORD Backend
# Simple approach: Let Cloud Run build and deploy directly

steps:
  # Deploy directly to Cloud Run - Cloud Run handles the build internally
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'galactly-backend'
      - '--source=.'
      - '--region=us-central1'
      - '--platform=managed'
      - '--generation=2'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--quiet'
    waitFor: ['-']

# Timeout for the entire build (60 minutes to account for Cloud Run build time)
timeout: '3600s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
