steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/galactly-backend'
      - '.'
    env:
      - 'CLOUDSDK_BUILD_NOTIFIER=false'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/galactly-backend'
    env:
      - 'CLOUDSDK_BUILD_NOTIFIER=false'

  # Deploy to Cloud Run with public access
  - name: 'gcr.io/cloud-builders/run'
    args:
      - 'deploy'
      - 'galactly-backend'
      - '--image=gcr.io/$PROJECT_ID/galactly-backend'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
    env:
      - 'CLOUDSDK_BUILD_NOTIFIER=false'

images:
  - 'gcr.io/$PROJECT_ID/galactly-backend'

logsBucket: null
